/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author dafin
 */
import database.ListFigure;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class Update extends javax.swing.JFrame {
    ListFigure Figure;

    /**
     * Creates new form Order
     */
    public Update() throws ClassNotFoundException, SQLException {
        Figure = new ListFigure();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formNama = new javax.swing.JTextField();
        formUkuran = new javax.swing.JTextField();
        formJenis = new javax.swing.JTextField();
        addDatas = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        formID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formNama.setBackground(new java.awt.Color(204, 204, 204));
        formNama.setText("Masukkan Nama");
        formNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formNamaActionPerformed(evt);
            }
        });
        getContentPane().add(formNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 210, 30));

        formUkuran.setBackground(new java.awt.Color(204, 204, 204));
        formUkuran.setText("Masukkan Ukuran");
        formUkuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formUkuranActionPerformed(evt);
            }
        });
        getContentPane().add(formUkuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 210, 30));

        formJenis.setBackground(new java.awt.Color(204, 204, 204));
        formJenis.setText("Masukkan Jenis");
        formJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formJenisActionPerformed(evt);
            }
        });
        getContentPane().add(formJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 210, 30));

        addDatas.setBackground(new java.awt.Color(204, 204, 204));
        addDatas.setText("Ubah");
        addDatas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDatasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addDatasMouseEntered(evt);
            }
        });
        addDatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDatasActionPerformed(evt);
            }
        });
        getContentPane().add(addDatas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 90, 30));

        cancel.setBackground(new java.awt.Color(204, 204, 204));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 90, 30));

        formID.setBackground(new java.awt.Color(204, 204, 204));
        formID.setText("Masukkan ID");
        formID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formIDActionPerformed(evt);
            }
        });
        getContentPane().add(formID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 210, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/04.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formNamaActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
        try {
            new MenuFigure().setVisible(true);     // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancelActionPerformed

    private void formUkuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formUkuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formUkuranActionPerformed

    private void formJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formJenisActionPerformed

    private void addDatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDatasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDatasActionPerformed

    private void addDatasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDatasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addDatasMouseEntered

    private void addDatasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDatasMouseClicked
        int id = Integer.parseInt(formID.getText());
        String nm = formNama.getText();
        String uk = formUkuran.getText();
        String je = formJenis.getText();
        
        if(!(je.isEmpty())){
        try {
            Figure.updateFigure(id,nm, uk, je);
        } catch (Exception ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, "UBAH DATA BERHASIL");
        
        try {
            new MenuFigure().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        }else{
        Figure.insertFigure(nm,uk);
        if(!(uk.isEmpty())){
        }else{
            Figure.insertFigure(nm);
        }
        if(!(nm.isEmpty())){
        }else{
            JOptionPane.showMessageDialog(null, "Anda Lupa Memasukkan Nama");
        }
        }
    }//GEN-LAST:event_addDatasMouseClicked

    private void formIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formIDActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDatas;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField formID;
    private javax.swing.JTextField formJenis;
    private javax.swing.JTextField formNama;
    private javax.swing.JTextField formUkuran;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
